import Head from 'next/head';
import HeaderImage from '@/components/Louie';
import Nav from '@/components/Nav';

export default function Home() {
  return (
    <>
      <Head>
        <title>GVSU Sports Analytics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="image x-icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <HeaderImage />
    </>
  )
}
