import Head from "next/head";
import Nav from "@/components/Nav";
import { Title, Container } from "@mantine/core";
import { useRouter } from "next/router";


export default function Sport() {
    const { asPath } = useRouter();
    const cleanPath = asPath.split('#')[0].split('?')[0].split("/");
    const sport = cleanPath[cleanPath.length - 1]
    return (
        <>
            <Head>
                <title>GVSU { sport } Analytics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="image x-icon" href="/favicon.ico" />
            </Head>
            <Nav></Nav>
            <Container>
                <Title>
                    This is the { sport } page.
                </Title>
            </Container>
        </>
    )
}
