import Head from "next/head";
import Nav from "@/components/Nav";
import { useRouter } from "next/router";


function getSport() {
    let router = useRouter();
    let { sport } = router.query;
    return sport
}


export default function Sport() {
    const sport = getSport();
    return (
        <>
            <Head>
                <title>GVSU { sport ? sport : 'Sports' } Analytics</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="image x-icon" href="/favicon.ico" />
            </Head>
            <Nav></Nav>
            <div>
                <h1 
                className="relative z-1 pt-4 text-center text-2xl font-bold">
                    This is the GVSU { sport ? sport : 'Sports' } Analytics page.
                </h1>
            </div>
        </>
    )
}
